import { useEffect, useRef, useState, type FormEvent } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { CalendarClock, Clock3, Pause, Pencil, Play, Plus, Trash2 } from 'lucide-react'
import { ApiError } from '../../api'
import { defineTranslations, useLanguage, useTranslations } from '../../i18n'
import { useNotices, useQueryErrorNotice } from '../../notices'
import { Button, ConfirmDialog, EmptyState, Field, Input, PageHeader, StatusBadge, Textarea } from '../../shared/ui'
import { AppPageShell } from '../shell/AppPageShell'
import { ManagementLoading, ManagementSheet, OverviewCard, OverviewGrid } from '../management/Management'
import { automationsApi, type Automation, type AutomationInput, type DeliveryDestination, type TimingInput } from './api'
import './AutomationsPage.css'

const messages = defineTranslations({
  eyebrow: 'Simply handled', title: 'Automations', description: 'Give Selu something to take care of on a schedule. Pause or change it whenever you like.', newAutomation: 'New automation', timezone: 'Timezone', timezoneDescription: 'Selu uses this timezone when you describe a time.', saveTimezone: 'Save timezone', timezoneSaved: 'Timezone updated', running: 'Running', paused: 'Paused', next: 'Next: {date}', noNext: 'No next run', edit: 'Edit', pause: 'Pause', resume: 'Resume', remove: 'Remove', empty: 'Nothing scheduled yet', emptyBody: 'Create an automation for something Selu should handle later or regularly.', createTitle: 'New automation', editTitle: 'Edit automation', editorDescription: 'Describe the result you want and when it should happen.', name: 'Name', namePlaceholder: 'Morning briefing', prompt: 'What should Selu do?', promptPlaceholder: 'Summarize my priorities and anything that needs attention.', when: 'When should it happen?', whenPlaceholder: 'Every weekday at 8 in the morning', whenHint: 'Use everyday words. Selu will turn them into a schedule when you save.', delivery: 'Where should the result go?', noDestinations: 'No active destination is available yet. Connect Web chat or another destination first.', moreTiming: 'More timing options', natural: 'Describe it in your own words', once: 'One time', exact: 'Exact repeating schedule', oneTime: 'Date and time', exactSchedule: 'Schedule expression', exactHint: 'Advanced: use a standard five-part cron expression.', scheduleDescription: 'Plain-language summary', save: 'Save automation', cancel: 'Cancel', close: 'Close panel', saved: 'Automation saved', stateSaved: 'Automation updated', deleteTitle: 'Remove this automation?', deleteBody: 'Future runs will stop and this automation will be removed. This cannot be undone.', deleted: 'Automation removed', required: 'Complete the highlighted fields before saving.', loadError: 'Automations could not be loaded', saveError: 'The automation was not saved', providerUnavailable: 'Selu could not understand that timing right now. Try the exact timing options instead.', web: 'Web chat', unknownDate: 'Date unavailable',
}, {
  eyebrow: 'Einfach erledigt', title: 'Automatisierungen', description: 'Gib Selu etwas, das später oder regelmäßig erledigt werden soll. Du kannst es jederzeit pausieren oder ändern.', newAutomation: 'Neue Automatisierung', timezone: 'Zeitzone', timezoneDescription: 'Selu verwendet diese Zeitzone, wenn du eine Uhrzeit beschreibst.', saveTimezone: 'Zeitzone speichern', timezoneSaved: 'Zeitzone aktualisiert', running: 'Aktiv', paused: 'Pausiert', next: 'Als Nächstes: {date}', noNext: 'Kein nächster Lauf', edit: 'Bearbeiten', pause: 'Pausieren', resume: 'Fortsetzen', remove: 'Entfernen', empty: 'Noch nichts geplant', emptyBody: 'Erstelle eine Automatisierung für etwas, das Selu später oder regelmäßig erledigen soll.', createTitle: 'Neue Automatisierung', editTitle: 'Automatisierung bearbeiten', editorDescription: 'Beschreibe das gewünschte Ergebnis und wann es passieren soll.', name: 'Name', namePlaceholder: 'Morgendlicher Überblick', prompt: 'Was soll Selu tun?', promptPlaceholder: 'Fasse meine Prioritäten und alles zusammen, was Aufmerksamkeit braucht.', when: 'Wann soll es passieren?', whenPlaceholder: 'Jeden Werktag um 8 Uhr morgens', whenHint: 'Beschreibe es mit normalen Worten. Selu erstellt beim Speichern den Zeitplan.', delivery: 'Wohin soll das Ergebnis gehen?', noDestinations: 'Noch ist kein aktives Ziel verfügbar. Verbinde zuerst den Web-Chat oder ein anderes Ziel.', moreTiming: 'Weitere Zeitoptionen', natural: 'Mit eigenen Worten beschreiben', once: 'Einmalig', exact: 'Exakter wiederkehrender Zeitplan', oneTime: 'Datum und Uhrzeit', exactSchedule: 'Zeitplan-Ausdruck', exactHint: 'Erweitert: Verwende einen üblichen fünfteiligen Cron-Ausdruck.', scheduleDescription: 'Verständliche Zusammenfassung', save: 'Automatisierung speichern', cancel: 'Abbrechen', close: 'Bereich schließen', saved: 'Automatisierung gespeichert', stateSaved: 'Automatisierung aktualisiert', deleteTitle: 'Diese Automatisierung entfernen?', deleteBody: 'Zukünftige Läufe werden gestoppt und die Automatisierung wird entfernt. Das kann nicht rückgängig gemacht werden.', deleted: 'Automatisierung entfernt', required: 'Fülle vor dem Speichern die markierten Felder aus.', loadError: 'Automatisierungen konnten nicht geladen werden', saveError: 'Die Automatisierung wurde nicht gespeichert', providerUnavailable: 'Selu konnte diese Zeitangabe gerade nicht verstehen. Nutze stattdessen die exakten Zeitoptionen.', web: 'Web-Chat', unknownDate: 'Datum nicht verfügbar',
})
type Copy = { [K in keyof typeof messages.en]: string }

export function AutomationsPage() {
  const copy = useTranslations(messages), language = useLanguage(), notices = useNotices(), cache = useQueryClient()
  const list = useQuery({ queryKey: ['automations'], queryFn: automationsApi.list })
  const destinations = useQuery({ queryKey: ['automation-destinations'], queryFn: automationsApi.destinations })
  const profile = useQuery({ queryKey: ['account', 'timezone'], queryFn: automationsApi.profile })
  useQueryErrorNotice(list.error ?? destinations.error ?? profile.error, copy.loadError)
  const [editor, setEditor] = useState<Automation | 'new' | null>(null), [deleting, setDeleting] = useState<Automation | null>(null), [timezoneOpen, setTimezoneOpen] = useState(false)
  const refresh = () => cache.invalidateQueries({ queryKey: ['automations'] })
  const save = useMutation({ mutationFn: ({ current, input }: { current: Automation | 'new'; input: AutomationInput }) => current === 'new' ? automationsApi.create(input) : automationsApi.update(current.id, input), onSuccess: () => { setEditor(null); void refresh(); notices.success(copy.saved) }, onError: (error) => error instanceof ApiError && error.code === 'automation.timing_provider_unavailable' ? notices.notify({ kind: 'error', title: copy.saveError, body: copy.providerUnavailable }) : notices.error(error, copy.saveError) })
  const toggle = useMutation({ mutationFn: ({ item, active }: { item: Automation; active: boolean }) => automationsApi.setActive(item.id, active), onSuccess: () => { void refresh(); notices.success(copy.stateSaved) }, onError: (error) => notices.error(error, copy.saveError) })
  const remove = useMutation({ mutationFn: (id: string) => automationsApi.remove(id), onSuccess: () => { setDeleting(null); void refresh(); notices.success(copy.deleted) }, onError: (error) => notices.error(error, copy.saveError) })
  const changeTimezone = useMutation({ mutationFn: automationsApi.setTimezone, onSuccess: (result) => { cache.setQueryData(['account', 'timezone'], { timezone: result.timezone }); setTimezoneOpen(false); notices.success(copy.timezoneSaved) }, onError: (error) => notices.error(error, copy.saveError) })
  const items = list.data?.automations ?? []
  return <AppPageShell active="automations" width="wide"><PageHeader eyebrow={copy.eyebrow} title={copy.title} description={copy.description} actions={<><Button onClick={() => setTimezoneOpen(true)} leadingIcon={<Clock3 />}>{copy.timezone}</Button><Button variant="primary" onClick={() => setEditor('new')} leadingIcon={<Plus />}>{copy.newAutomation}</Button></>} />
    {list.isPending || destinations.isPending ? <ManagementLoading /> : items.length ? <OverviewGrid>{items.map((item) => <OverviewCard key={item.id} icon={<CalendarClock />} status={<StatusBadge tone={item.active ? 'success' : 'neutral'}>{item.active ? copy.running : copy.paused}</StatusBadge>} title={item.name} description={<><span className="automation-timing">{item.timing.description}</span><span className="automation-prompt">{item.prompt}</span></>} meta={item.active ? copy.next.replace('{date}', formatDate(item.next_run_at, language, copy.unknownDate)) : copy.noNext} actions={<><Button size="sm" variant="ghost" onClick={() => toggle.mutate({ item, active: !item.active })} leadingIcon={item.active ? <Pause /> : <Play />}>{item.active ? copy.pause : copy.resume}</Button><Button size="sm" onClick={() => setEditor(item)} leadingIcon={<Pencil />}>{copy.edit}</Button><Button size="sm" variant="ghost" onClick={() => setDeleting(item)} leadingIcon={<Trash2 />}>{copy.remove}</Button></>} />)}</OverviewGrid> : <EmptyState icon={<CalendarClock />} title={copy.empty} description={copy.emptyBody} action={<Button variant="primary" onClick={() => setEditor('new')} leadingIcon={<Plus />}>{copy.newAutomation}</Button>} />}
    <AutomationSheet current={editor} destinations={destinations.data?.destinations ?? []} timezone={profile.data?.timezone ?? 'UTC'} copy={copy} busy={save.isPending} onClose={() => setEditor(null)} onSave={(input) => editor && save.mutate({ current: editor, input })} />
    <TimezoneSheet open={timezoneOpen} initial={profile.data?.timezone ?? 'UTC'} copy={copy} busy={changeTimezone.isPending} onClose={() => setTimezoneOpen(false)} onSave={(value) => changeTimezone.mutate(value)} />
    <ConfirmDialog open={Boolean(deleting)} title={copy.deleteTitle} message={copy.deleteBody} confirmLabel={copy.remove} cancelLabel={copy.cancel} destructive busy={remove.isPending} onCancel={() => setDeleting(null)} onConfirm={() => deleting && remove.mutate(deleting.id)} />
  </AppPageShell>
}

function AutomationSheet({ current, destinations, timezone, copy, busy, onClose, onSave }: { current: Automation | 'new' | null; destinations: DeliveryDestination[]; timezone: string; copy: Copy; busy: boolean; onClose: () => void; onSave: (input: AutomationInput) => void }) {
  const form = useRef<HTMLFormElement>(null), [name, setName] = useState(''), [prompt, setPrompt] = useState(''), [selected, setSelected] = useState<string[]>([]), [mode, setMode] = useState<'natural' | 'once' | 'cron'>('natural'), [timingText, setTimingText] = useState(''), [fireAt, setFireAt] = useState(''), [cron, setCron] = useState(''), [summary, setSummary] = useState(''), [zone, setZone] = useState(timezone), [error, setError] = useState('')
  useEffect(() => { if (!current) return; setName(current === 'new' ? '' : current.name); setPrompt(current === 'new' ? '' : current.prompt); setSelected(current === 'new' ? destinations.slice(0, 1).map((item) => item.pipe_id) : current.pipe_ids); setMode(current === 'new' ? 'natural' : current.timing.type === 'one_shot' ? 'once' : 'cron'); setTimingText(''); setFireAt(current !== 'new' && current.timing.type === 'one_shot' ? toLocalDateTime(current.timing.fire_at) : ''); setCron(current !== 'new' && current.timing.type === 'recurring' ? current.timing.cron_expression : ''); setSummary(current === 'new' ? '' : current.timing.description); setZone(current === 'new' ? timezone : current.timing.timezone); setError('') }, [current, destinations, timezone])
  const submit = (event: FormEvent) => { event.preventDefault(); if (!name.trim() || !prompt.trim() || !selected.length || (mode === 'natural' && !timingText.trim()) || (mode === 'once' && !fireAt) || (mode === 'cron' && !cron.trim())) { setError(copy.required); return } const timing: TimingInput = mode === 'natural' ? { type: 'natural_language', text: timingText.trim(), timezone: zone } : mode === 'once' ? { type: 'one_shot', fire_at: new Date(fireAt).toISOString(), description: summary.trim() || undefined, timezone: zone } : { type: 'cron', cron_expression: cron.trim(), description: summary.trim() || undefined, timezone: zone }; onSave({ name: name.trim(), prompt: prompt.trim(), pipe_ids: selected, timing }) }
  return <ManagementSheet open={Boolean(current)} title={current === 'new' ? copy.createTitle : copy.editTitle} description={copy.editorDescription} closeLabel={copy.close} onClose={onClose} busy={busy} actions={<><Button onClick={onClose} disabled={busy}>{copy.cancel}</Button><Button variant="primary" loading={busy} onClick={() => form.current?.requestSubmit()}>{copy.save}</Button></>}><form ref={form} className="management-form" onSubmit={submit}>{error && <div className="management-inline-error">{error}</div>}<Field label={copy.name}><Input value={name} onChange={(event) => setName(event.target.value)} placeholder={copy.namePlaceholder} maxLength={120} /></Field><Field label={copy.prompt}><Textarea rows={4} value={prompt} onChange={(event) => setPrompt(event.target.value)} placeholder={copy.promptPlaceholder} /></Field>{mode === 'natural' && <Field label={copy.when} hint={copy.whenHint}><Input value={timingText} onChange={(event) => setTimingText(event.target.value)} placeholder={copy.whenPlaceholder} /></Field>}<Field label={copy.delivery}>{destinations.length ? <div className="management-choice-list">{destinations.map((item) => <label className="management-choice" key={item.pipe_id}><input type="checkbox" checked={selected.includes(item.pipe_id)} onChange={() => setSelected((values) => values.includes(item.pipe_id) ? values.filter((id) => id !== item.pipe_id) : [...values, item.pipe_id])} /><span>{item.name}<small>{item.transport === 'web' ? copy.web : item.transport}</small></span></label>)}</div> : <div className="management-inline-error">{copy.noDestinations}</div>}</Field><details open={mode !== 'natural'}><summary>{copy.moreTiming}</summary><div><div className="management-choice-list">{(['natural', 'once', 'cron'] as const).map((value) => <label className="management-choice" key={value}><input type="radio" name="timing-mode" checked={mode === value} onChange={() => setMode(value)} /><span>{value === 'natural' ? copy.natural : value === 'once' ? copy.once : copy.exact}</span></label>)}</div>{mode === 'once' && <Field label={copy.oneTime}><Input type="datetime-local" value={fireAt} onChange={(event) => setFireAt(event.target.value)} /></Field>}{mode === 'cron' && <Field label={copy.exactSchedule} hint={copy.exactHint}><Input value={cron} onChange={(event) => setCron(event.target.value)} placeholder="0 8 * * 1-5" /></Field>}{mode !== 'natural' && <Field label={copy.scheduleDescription}><Input value={summary} onChange={(event) => setSummary(event.target.value)} /></Field>}<Field label={copy.timezone}><Input value={zone} onChange={(event) => setZone(event.target.value)} /></Field></div></details></form></ManagementSheet>
}
function TimezoneSheet({ open, initial, copy, busy, onClose, onSave }: { open: boolean; initial: string; copy: Copy; busy: boolean; onClose: () => void; onSave: (value: string) => void }) { const [value, setValue] = useState(initial); useEffect(() => { if (open) setValue(initial) }, [open, initial]); return <ManagementSheet open={open} title={copy.timezone} description={copy.timezoneDescription} closeLabel={copy.close} onClose={onClose} busy={busy} actions={<><Button onClick={onClose}>{copy.cancel}</Button><Button variant="primary" loading={busy} onClick={() => onSave(value.trim())}>{copy.saveTimezone}</Button></>}><Field label={copy.timezone}><Input value={value} onChange={(event) => setValue(event.target.value)} /></Field></ManagementSheet> }
function formatDate(value: string, language: string, fallback: string) { const date = new Date(value); return Number.isNaN(date.valueOf()) ? fallback : new Intl.DateTimeFormat(language, { dateStyle: 'medium', timeStyle: 'short' }).format(date) }
function toLocalDateTime(value: string) { const date = new Date(value); if (Number.isNaN(date.valueOf())) return ''; const offset = date.getTimezoneOffset() * 60_000; return new Date(date.getTime() - offset).toISOString().slice(0, 16) }
