import { useEffect, useRef, useState, type FormEvent } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { KeyRound, Pencil, Plus, ShieldCheck, Trash2, UserRound, Users } from 'lucide-react'
import { api, ApiError } from '../../api'
import { authStateQuery } from '../auth/AuthPages'
import { defineTranslations, useLanguage, useTranslations } from '../../i18n'
import { useNotices, useQueryErrorNotice } from '../../notices'
import { Button, ConfirmDialog, EmptyState, Field, Input, PageHeader, SecretField, StatusBadge } from '../../shared/ui'
import { AppPageShell } from '../shell/AppPageShell'
import { ManagementLoading, ManagementSheet, OverviewCard, OverviewGrid } from '../management/Management'
import { peopleApi, type CreatePerson, type Person } from './api'
import './PeoplePage.css'

const messages = defineTranslations({
  eyebrow: 'Manage access', title: 'People', description: 'Choose who can use this Selu and which helpers are available to them.', add: 'Add a person', administrator: 'Administrator', person: 'Person', you: 'You', joined: 'Joined {date}', edit: 'Edit', remove: 'Remove', noPeople: 'No people found', noPeopleBody: 'Add someone when you are ready to share this Selu.', forbidden: 'Only an administrator can manage people.', createTitle: 'Add a person', editTitle: 'Edit {name}', editorDescription: 'Sign-in details and access for this person.', displayName: 'Name', username: 'Username', password: 'Temporary password', passwordHint: 'Use at least 8 characters. Share it privately.', language: 'Language', english: 'English', german: 'German', timezone: 'Timezone', adminAccess: 'Administrator access', adminHint: 'Administrators can manage people, connections, and shared settings.', helperAccess: 'Which helpers can they use?', allHelpers: 'All available helpers', allHelpersHint: 'New helpers are included automatically.', noHelpers: 'No helpers', noHelpersHint: 'They can sign in, but cannot use an agent.', selectedHelpers: 'Keep their current selection', selectedHelpersHint: 'This account currently has a custom helper selection.', save: 'Save person', cancel: 'Cancel', close: 'Close panel', saved: 'Person saved', saveError: 'The person was not saved', deleteTitle: 'Remove this person?', deleteBody: 'They will no longer be able to sign in. Their account data will be removed.', deleted: 'Person removed', selfDelete: 'You cannot remove your own account here.', lastAdmin: 'At least one administrator must remain.', required: 'Enter a name, username, and password of at least 8 characters.', loadError: 'People could not be loaded', show: 'Show password', hide: 'Hide password', customCount: '{count} selected helpers',
}, {
  eyebrow: 'Zugriff verwalten', title: 'Personen', description: 'Lege fest, wer dieses Selu verwenden kann und welche Helfer verfügbar sind.', add: 'Person hinzufügen', administrator: 'Administrator', person: 'Person', you: 'Du', joined: 'Dabei seit {date}', edit: 'Bearbeiten', remove: 'Entfernen', noPeople: 'Keine Personen gefunden', noPeopleBody: 'Füge jemanden hinzu, wenn du dieses Selu teilen möchtest.', forbidden: 'Nur Administratoren können Personen verwalten.', createTitle: 'Person hinzufügen', editTitle: '{name} bearbeiten', editorDescription: 'Anmeldedaten und Zugriff für diese Person.', displayName: 'Name', username: 'Benutzername', password: 'Vorläufiges Passwort', passwordHint: 'Verwende mindestens 8 Zeichen und teile es privat.', language: 'Sprache', english: 'Englisch', german: 'Deutsch', timezone: 'Zeitzone', adminAccess: 'Administratorzugriff', adminHint: 'Administratoren können Personen, Verbindungen und gemeinsame Einstellungen verwalten.', helperAccess: 'Welche Helfer darf die Person verwenden?', allHelpers: 'Alle verfügbaren Helfer', allHelpersHint: 'Neue Helfer werden automatisch eingeschlossen.', noHelpers: 'Keine Helfer', noHelpersHint: 'Die Person kann sich anmelden, aber keinen Agenten verwenden.', selectedHelpers: 'Aktuelle Auswahl behalten', selectedHelpersHint: 'Für dieses Konto ist eine eigene Helferauswahl gespeichert.', save: 'Person speichern', cancel: 'Abbrechen', close: 'Bereich schließen', saved: 'Person gespeichert', saveError: 'Die Person wurde nicht gespeichert', deleteTitle: 'Diese Person entfernen?', deleteBody: 'Die Person kann sich danach nicht mehr anmelden. Ihre Kontodaten werden entfernt.', deleted: 'Person entfernt', selfDelete: 'Du kannst dein eigenes Konto hier nicht entfernen.', lastAdmin: 'Mindestens ein Administrator muss bestehen bleiben.', required: 'Gib Name, Benutzername und ein Passwort mit mindestens 8 Zeichen ein.', loadError: 'Personen konnten nicht geladen werden', show: 'Passwort anzeigen', hide: 'Passwort ausblenden', customCount: '{count} ausgewählte Helfer',
})
type Copy = { [K in keyof typeof messages.en]: string }
type AccessMode = 'all' | 'none' | 'selected'

export function PeoplePage() {
  const copy = useTranslations(messages), language = useLanguage(), notices = useNotices(), cache = useQueryClient()
  const people = useQuery({ queryKey: ['people'], queryFn: peopleApi.list, retry: false })
  const auth = useQuery({ ...authStateQuery, queryFn: api.authState })
  useQueryErrorNotice(people.error && !(people.error instanceof ApiError && people.error.status === 403) ? people.error : null, copy.loadError)
  const [editor, setEditor] = useState<Person | 'new' | null>(null), [deleting, setDeleting] = useState<Person | null>(null)
  const refresh = () => cache.invalidateQueries({ queryKey: ['people'] })
  const save = useMutation({ mutationFn: async ({ current, input, access }: { current: Person | 'new'; input: CreatePerson; access: AccessMode }) => { const person = current === 'new' ? await peopleApi.create(input) : await peopleApi.update(current.id, { username: input.username, display_name: input.display_name, is_admin: input.is_admin, language: input.language, timezone: input.timezone }); const ids = access === 'all' ? [] : access === 'none' ? ['__none__'] : current === 'new' ? [] : current.allowed_agent_ids; await peopleApi.setAgentAccess(person.id, ids); return person }, onSuccess: () => { setEditor(null); void refresh(); notices.success(copy.saved) }, onError: (error) => accountNotice(error, copy, notices, copy.saveError) })
  const remove = useMutation({ mutationFn: (id: string) => peopleApi.remove(id), onSuccess: () => { setDeleting(null); void refresh(); notices.success(copy.deleted) }, onError: (error) => accountNotice(error, copy, notices, copy.saveError) })
  const currentId = auth.data?.user?.user_id
  const forbidden = people.error instanceof ApiError && people.error.status === 403
  return <AppPageShell active="people" width="wide"><PageHeader eyebrow={copy.eyebrow} title={copy.title} description={copy.description} actions={!forbidden && <Button variant="primary" leadingIcon={<Plus />} onClick={() => setEditor('new')}>{copy.add}</Button>} />
    {people.isPending ? <ManagementLoading /> : forbidden ? <EmptyState icon={<ShieldCheck />} title={copy.forbidden} /> : people.data?.length ? <OverviewGrid>{people.data.map((person) => { const own = person.id === currentId; return <OverviewCard key={person.id} icon={<UserRound />} status={<StatusBadge tone={person.is_admin ? 'info' : 'neutral'}>{person.is_admin ? copy.administrator : copy.person}</StatusBadge>} title={<>{person.display_name}{own && <small className="people-you">{copy.you}</small>}</>} description={`@${person.username}`} meta={copy.joined.replace('{date}', formatDate(person.created_at, language))} actions={<><Button size="sm" leadingIcon={<Pencil />} onClick={() => setEditor(person)}>{copy.edit}</Button><Button size="sm" variant="ghost" leadingIcon={<Trash2 />} disabled={own} title={own ? copy.selfDelete : undefined} onClick={() => setDeleting(person)}>{copy.remove}</Button></>}><div className="people-access"><KeyRound />{person.allowed_agent_ids.length === 0 ? copy.allHelpers : person.allowed_agent_ids[0] === '__none__' ? copy.noHelpers : copy.customCount.replace('{count}', String(person.allowed_agent_ids.length))}</div></OverviewCard> })}</OverviewGrid> : <EmptyState icon={<Users />} title={copy.noPeople} description={copy.noPeopleBody} action={<Button variant="primary" leadingIcon={<Plus />} onClick={() => setEditor('new')}>{copy.add}</Button>} />}
    <PersonSheet current={editor} copy={copy} busy={save.isPending} onClose={() => setEditor(null)} onSave={(input, access) => editor && save.mutate({ current: editor, input, access })} />
    <ConfirmDialog open={Boolean(deleting)} title={copy.deleteTitle} message={copy.deleteBody} confirmLabel={copy.remove} cancelLabel={copy.cancel} destructive busy={remove.isPending} onCancel={() => setDeleting(null)} onConfirm={() => deleting && remove.mutate(deleting.id)} />
  </AppPageShell>
}

function PersonSheet({ current, copy, busy, onClose, onSave }: { current: Person | 'new' | null; copy: Copy; busy: boolean; onClose: () => void; onSave: (input: CreatePerson, access: AccessMode) => void }) {
  const form = useRef<HTMLFormElement>(null), [name, setName] = useState(''), [username, setUsername] = useState(''), [password, setPassword] = useState(''), [admin, setAdmin] = useState(false), [locale, setLocale] = useState<'en' | 'de'>('en'), [timezone, setTimezone] = useState(Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC'), [access, setAccess] = useState<AccessMode>('all'), [error, setError] = useState('')
  useEffect(() => { if (!current) return; setName(current === 'new' ? '' : current.display_name); setUsername(current === 'new' ? '' : current.username); setPassword(''); setAdmin(current === 'new' ? false : current.is_admin); setLocale(current === 'new' ? 'en' : current.language === 'de' ? 'de' : 'en'); setTimezone(current === 'new' ? Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC' : current.timezone); setAccess(current === 'new' || current.allowed_agent_ids.length === 0 ? 'all' : current.allowed_agent_ids[0] === '__none__' ? 'none' : 'selected'); setError('') }, [current])
  const submit = (event: FormEvent) => { event.preventDefault(); if (!name.trim() || !username.trim() || current === 'new' && password.length < 8) { setError(copy.required); return } onSave({ display_name: name.trim(), username: username.trim(), password, is_admin: admin, language: locale, timezone: timezone.trim() }, access) }
  return <ManagementSheet open={Boolean(current)} title={current === 'new' ? copy.createTitle : copy.editTitle.replace('{name}', current?.display_name ?? '')} description={copy.editorDescription} closeLabel={copy.close} onClose={onClose} busy={busy} actions={<><Button onClick={onClose} disabled={busy}>{copy.cancel}</Button><Button variant="primary" loading={busy} onClick={() => form.current?.requestSubmit()}>{copy.save}</Button></>}><form ref={form} className="management-form" onSubmit={submit}>{error && <div className="management-inline-error">{error}</div>}<Field label={copy.displayName}><Input value={name} onChange={(event) => setName(event.target.value)} maxLength={120} /></Field><Field label={copy.username}><Input value={username} onChange={(event) => setUsername(event.target.value)} maxLength={80} autoCapitalize="none" /></Field>{current === 'new' && <Field label={copy.password} hint={copy.passwordHint}><SecretField value={password} onChange={(event) => setPassword(event.target.value)} autoComplete="new-password" showLabel={copy.show} hideLabel={copy.hide} /></Field>}<div className="management-form-row"><Field label={copy.language}><select className="selu-ui-control selu-ui-select" value={locale} onChange={(event) => setLocale(event.target.value as 'en' | 'de')}><option value="en">{copy.english}</option><option value="de">{copy.german}</option></select></Field><Field label={copy.timezone}><Input value={timezone} onChange={(event) => setTimezone(event.target.value)} /></Field></div><label className="management-choice"><input type="checkbox" checked={admin} onChange={(event) => setAdmin(event.target.checked)} /><span>{copy.adminAccess}<small>{copy.adminHint}</small></span></label><Field label={copy.helperAccess}><div className="management-choice-list">{(['all', 'none', ...(current !== 'new' && current?.allowed_agent_ids.length && current.allowed_agent_ids[0] !== '__none__' ? ['selected'] : [])] as AccessMode[]).map((mode) => <label className="management-choice" key={mode}><input type="radio" name="agent-access" checked={access === mode} onChange={() => setAccess(mode)} /><span>{mode === 'all' ? copy.allHelpers : mode === 'none' ? copy.noHelpers : copy.selectedHelpers}<small>{mode === 'all' ? copy.allHelpersHint : mode === 'none' ? copy.noHelpersHint : copy.selectedHelpersHint}</small></span></label>)}</div></Field></form></ManagementSheet>
}
function accountNotice(error: unknown, copy: Copy, notices: ReturnType<typeof useNotices>, title: string) { const body = error instanceof ApiError && error.code === 'last_admin_required' ? copy.lastAdmin : error instanceof ApiError && error.code === 'self_deletion_forbidden' ? copy.selfDelete : undefined; body ? notices.notify({ kind: 'error', title, body }) : notices.error(error, title) }
function formatDate(value: string, language: string) { const date = new Date(value); return Number.isNaN(date.valueOf()) ? '' : new Intl.DateTimeFormat(language, { dateStyle: 'medium' }).format(date) }
